    # 配置服务 原理培训
    server {
        listen       8084;
        server_name  127.0.0.1;

        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
            try_files $uri =404;
        }

        location / {
            root   html/child/PrinciplesTraining;
            index  index.html index.htm;
            try_files     $uri $uri/ /index.html;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        # 配置服务 原理培训后端地址
        location /api/ {
            # rewrite ^/api(.*) /$1 break;
            proxy_pass    http://127.0.0.1:9904/;
            proxy_set_header Host $host;
            proxy_set_header X-real-ip $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # When setting up Harbor behind other proxy, such as an Nginx instance, remove the below line if the proxy already has similar settings.
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_buffering off;
            proxy_request_buffering off;

        }
        # 配置服务 培训管理后端地址
        location /trainingManagement/api/ {
            # rewrite ^/api(.*) /$1 break;
            proxy_pass    http://127.0.0.1:9904/;
            proxy_set_header Host $host;
            proxy_set_header X-real-ip $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # When setting up Harbor behind other proxy, such as an Nginx instance, remove the below line if the proxy already has similar settings.
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_buffering off;
            proxy_request_buffering off;

        }
    }